#ifndef ORBITER_POWER_EVENTS_H
#define ORBITER_POWER_EVENTS_H

#define ORBITER_POWER_STARTUP_INF_EID                1U
#define ORBITER_POWER_CMD_ERR_EID                    2U
#define ORBITER_POWER_CMD_NOOP_INF_EID               3U
#define ORBITER_POWER_LOAD_SWITCH_INF_EID            4U
#define ORBITER_POWER_LOAD_SWITCH_PROHIBITED_ERR_EID 5U
#define ORBITER_POWER_LOAD_SWITCH_BOUNDS_ERR_EID     6U
#define ORBITER_POWER_MODE_SET_INF_EID               7U
#define ORBITER_POWER_MODE_INVALID_ERR_EID           8U

#define ORBITER_POWER_EVENT_COUNT                    8U

#endif /* ORBITER_POWER_EVENTS_H */
