#ifndef ORBITER_POWER_VERSION_H
#define ORBITER_POWER_VERSION_H

#define ORBITER_POWER_MAJOR_VERSION  1
#define ORBITER_POWER_MINOR_VERSION  0
#define ORBITER_POWER_REVISION       0

#endif /* ORBITER_POWER_VERSION_H */
