#![deny(clippy::all)]
// Allow bindgen-generated names that don't follow Rust conventions
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]

//! Safe Rust wrappers around compile-time constants from `_defs/mission_config.h`.
//!
//! The raw bindgen output is included below; safe wrapper types are defined
//! in this module to give callers a Rust-idiomatic interface.

include!(concat!(env!("OUT_DIR"), "/mission_config_bindings.rs"));

/// Mission configuration constants re-exported with idiomatic Rust names.
pub mod mission {
    // SAFETY: SAMPLE_MISSION_MAX_PIPES is a plain compile-time integer constant
    // generated by bindgen from a C #define. No pointer indirection or aliasing.
    pub const MAX_PIPES: u32 = super::SAMPLE_MISSION_MAX_PIPES;

    // SAFETY: same rationale as MAX_PIPES
    pub const TASK_STACK_BYTES: u32 = super::SAMPLE_MISSION_TASK_STACK;

    // SAFETY: same rationale as MAX_PIPES
    pub const SPACECRAFT_ID: u32 = super::SPACECRAFT_ID;
}

#[cfg(test)]
mod tests {
    use super::mission;

    #[test]
    fn test_max_pipes_is_nonzero() {
        assert!(mission::MAX_PIPES > 0, "mission must allow at least one pipe");
    }

    #[test]
    fn test_task_stack_is_power_of_two() {
        let stack = mission::TASK_STACK_BYTES;
        assert!(stack.is_power_of_two(), "stack size should be a power of two for alignment");
    }

    #[test]
    fn test_spacecraft_id_is_in_valid_apid_range() {
        /* CCSDS APIDs are 11-bit values (0–2047) */
        assert!(mission::SPACECRAFT_ID <= 2047, "spacecraft ID must fit in 11-bit APID field");
    }
}
