import type { CommandDef } from '../types/commands'

export const COMMANDS: CommandDef[] = [
  {
    id: 'cdh-noop',
    name: 'CDH NOOP',
    target: 'orbiter_cdh',
    apid: 0x181,
    funcCode: 0x00,
    description: 'Keep-alive ping to Command & Data Handling app',
    isSafetyInterlocked: false,
    category: 'orbiter',
  },
  {
    id: 'cdh-mode-nominal',
    name: 'CDH Mode → NOMINAL',
    target: 'orbiter_cdh',
    apid: 0x181,
    funcCode: 0x02,
    description: 'Transition spacecraft from SAFE to NOMINAL operations mode',
    isSafetyInterlocked: false,
    category: 'orbiter',
  },
  {
    id: 'adcs-identity-quat',
    name: 'ADCS Set Identity Quat',
    target: 'orbiter_adcs',
    apid: 0x182,
    funcCode: 0x02,
    description: 'Command attitude control to identity quaternion (no rotation)',
    isSafetyInterlocked: false,
    category: 'orbiter',
  },
  {
    id: 'comm-vc0-rate',
    name: 'COMM Set VC0 100 kbps',
    target: 'orbiter_comm',
    apid: 0x183,
    funcCode: 0x02,
    description: 'Boost VC-0 HK downlink rate to 100 kbps for high-cadence ops',
    isSafetyInterlocked: false,
    category: 'orbiter',
  },
  {
    id: 'comm-time-corr',
    name: 'COMM Time Correlation',
    target: 'orbiter_comm',
    apid: 0x183,
    funcCode: 0x03,
    description: 'Send time-correlation packet to sync spacecraft TAI clock',
    isSafetyInterlocked: false,
    category: 'orbiter',
  },
  {
    id: 'eps-safe',
    name: 'EPS Mode → SAFE',
    target: 'orbiter_power',
    apid: 0x184,
    funcCode: 0x03,
    description: 'Switch EPS to power-safe mode (reduces non-essential loads)',
    isSafetyInterlocked: false,
    category: 'orbiter',
  },
  {
    id: 'payload-pwr-on',
    name: 'Payload Power ON',
    target: 'orbiter_payload',
    apid: 0x185,
    funcCode: 0x02,
    description: 'Energize science payload for imaging session',
    isSafetyInterlocked: false,
    category: 'orbiter',
  },
  {
    id: 'land-nominal',
    name: 'Land Rover NOMINAL',
    target: 'rover_land',
    apid: 0x380,
    funcCode: 0x02,
    description: 'Set land rover to autonomous navigation mode',
    isSafetyInterlocked: false,
    category: 'rover',
  },
  {
    id: 'uav-loiter',
    name: 'UAV Set Loiter',
    target: 'rover_uav',
    apid: 0x3c0,
    funcCode: 0x02,
    description: 'Command UAV to hold current position and altitude',
    isSafetyInterlocked: false,
    category: 'rover',
  },
  {
    id: 'cryo-drill-500rpm',
    name: 'Cryobot Drill 500 RPM',
    target: 'rover_cryobot',
    apid: 0x440,
    funcCode: 0x82,
    description: 'Safety-interlocked: set drill speed to 500 RPM (confirm_magic=0xCB02)',
    isSafetyInterlocked: true,
    category: 'rover',
  },
]
