#ifndef ORBITER_ADCS_EVENTS_H
#define ORBITER_ADCS_EVENTS_H

#define ORBITER_ADCS_STARTUP_INF_EID           1U
#define ORBITER_ADCS_CMD_ERR_EID               2U
#define ORBITER_ADCS_CMD_NOOP_INF_EID          3U
#define ORBITER_ADCS_QUAT_ACCEPTED_INF_EID     4U
#define ORBITER_ADCS_QUAT_INVALID_ERR_EID      5U

#define ORBITER_ADCS_EVENT_COUNT               5U

#endif /* ORBITER_ADCS_EVENTS_H */
