#ifndef ORBITER_ADCS_VERSION_H
#define ORBITER_ADCS_VERSION_H

#define ORBITER_ADCS_MAJOR_VERSION  1
#define ORBITER_ADCS_MINOR_VERSION  0
#define ORBITER_ADCS_REVISION       0

#endif /* ORBITER_ADCS_VERSION_H */
