#ifndef ORBITER_PAYLOAD_VERSION_H
#define ORBITER_PAYLOAD_VERSION_H

#define ORBITER_PAYLOAD_MAJOR_VERSION  1
#define ORBITER_PAYLOAD_MINOR_VERSION  0
#define ORBITER_PAYLOAD_REVISION       0

#endif /* ORBITER_PAYLOAD_VERSION_H */
