#ifndef ORBITER_PAYLOAD_EVENTS_H
#define ORBITER_PAYLOAD_EVENTS_H

#define ORBITER_PAYLOAD_STARTUP_INF_EID             1U
#define ORBITER_PAYLOAD_CMD_ERR_EID                 2U
#define ORBITER_PAYLOAD_CMD_NOOP_INF_EID            3U
#define ORBITER_PAYLOAD_POWER_SET_INF_EID           4U
#define ORBITER_PAYLOAD_POWER_INVALID_ERR_EID       5U
#define ORBITER_PAYLOAD_SCIENCE_MODE_SET_INF_EID    6U
#define ORBITER_PAYLOAD_SCIENCE_MODE_INVALID_ERR_EID 7U
#define ORBITER_PAYLOAD_SCIENCE_MODE_POWER_ERR_EID  8U

#define ORBITER_PAYLOAD_EVENT_COUNT                 8U

#endif /* ORBITER_PAYLOAD_EVENTS_H */
