#ifndef ORBITER_CDH_EVENTS_H
#define ORBITER_CDH_EVENTS_H

#define ORBITER_CDH_STARTUP_INF_EID           1U
#define ORBITER_CDH_CMD_ERR_EID               2U
#define ORBITER_CDH_CMD_NOOP_INF_EID          3U
#define ORBITER_CDH_MODE_TRANSITION_INF_EID   4U
#define ORBITER_CDH_MODE_INVALID_ERR_EID      5U
#define ORBITER_CDH_EVS_FILTER_INF_EID        6U

#define ORBITER_CDH_EVENT_COUNT               6U

#endif /* ORBITER_CDH_EVENTS_H */
