#ifndef ORBITER_CDH_VERSION_H
#define ORBITER_CDH_VERSION_H

#define ORBITER_CDH_MAJOR_VERSION  1
#define ORBITER_CDH_MINOR_VERSION  0
#define ORBITER_CDH_REVISION       0

#endif /* ORBITER_CDH_VERSION_H */
