#ifndef SIM_ADAPTER_VERSION_H
#define SIM_ADAPTER_VERSION_H

#define SIM_ADAPTER_MAJOR_VERSION  1
#define SIM_ADAPTER_MINOR_VERSION  0
#define SIM_ADAPTER_REVISION       0

#endif /* SIM_ADAPTER_VERSION_H */
