#ifndef MCU_PAYLOAD_GW_EVENTS_H
#define MCU_PAYLOAD_GW_EVENTS_H

#define MCU_PAYLOAD_GW_STARTUP_INF_EID    1U
#define MCU_PAYLOAD_GW_CMD_ERR_EID        2U
#define MCU_PAYLOAD_GW_EEP_ERR_EID        3U
#define MCU_PAYLOAD_GW_BUS_SILENT_ERR_EID 4U

#define MCU_PAYLOAD_GW_EVENT_COUNT        4U

#endif /* MCU_PAYLOAD_GW_EVENTS_H */
