#ifndef ROS2_BRIDGE_VERSION_H
#define ROS2_BRIDGE_VERSION_H

#define ROS2_BRIDGE_MAJOR_VERSION  0
#define ROS2_BRIDGE_MINOR_VERSION  1
#define ROS2_BRIDGE_REVISION       0

#endif /* ROS2_BRIDGE_VERSION_H */
