#ifndef ORBITER_COMM_EVENTS_H
#define ORBITER_COMM_EVENTS_H

#define ORBITER_COMM_STARTUP_INF_EID              1U
#define ORBITER_COMM_CMD_ERR_EID                  2U
#define ORBITER_COMM_NOOP_INF_EID                 3U
#define ORBITER_COMM_RATE_SET_INF_EID             4U
#define ORBITER_COMM_VC_INVALID_ERR_EID           5U
#define ORBITER_COMM_RATE_INVALID_ERR_EID         6U
#define ORBITER_COMM_TCP_ACCEPTED_INF_EID         7U
#define ORBITER_COMM_CFDP_TXN_STARTED_INF_EID    8U
#define ORBITER_COMM_CFDP_TXN_COMPLETE_INF_EID   9U
#define ORBITER_COMM_LINK_STATE_INF_EID           10U

#define ORBITER_COMM_EVENT_COUNT                  10U

#endif /* ORBITER_COMM_EVENTS_H */
