#ifndef ORBITER_COMM_VERSION_H
#define ORBITER_COMM_VERSION_H

#define ORBITER_COMM_MAJOR_VERSION  1
#define ORBITER_COMM_MINOR_VERSION  0
#define ORBITER_COMM_REVISION       0

#endif /* ORBITER_COMM_VERSION_H */
